const DAYS_IN_WEEK = 7;
const CHART_INNER_RADIUS = 30;
const CHART_OUTER_RADIUS = 80;
const CHART_PADDING_ANGLE = 2;
const CHART_HEIGHT = 200;
const MAX_DISPLAYED_DOMAINS = 5;

export {
  DAYS_IN_WEEK,
  CHART_INNER_RADIUS,
  CHART_OUTER_RADIUS,
  CHART_PADDING_ANGLE,
  CHART_HEIGHT,
  MAX_DISPLAYED_DOMAINS,
};
