const MILLISECONDS_IN_SECOND = 1000;
const SECONDS_IN_MINUTE = 60;
const MINUTES_IN_HOUR = 60;

const MINUTES_TO_MS = SECONDS_IN_MINUTE * MILLISECONDS_IN_SECOND;
const HOURS_TO_MS = MINUTES_IN_HOUR * MINUTES_TO_MS;

const DEFAULT_TIME_LIMIT_HOURS = 1;
const DEFAULT_TIME_LIMIT = DEFAULT_TIME_LIMIT_HOURS * HOURS_TO_MS;

const ACTIVE_SESSION_REFRESH_INTERVAL = 5000;

export {
  MILLISECONDS_IN_SECOND,
  SECONDS_IN_MINUTE,
  MINUTES_IN_HOUR,
  MINUTES_TO_MS,
  HOURS_TO_MS,
  DEFAULT_TIME_LIMIT,
  ACTIVE_SESSION_REFRESH_INTERVAL,
};
